context:
  version: "2.16.44"

package:
  name: refinedev-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@refinedev/cli/-/cli-${{ version }}.tgz
  sha256: b0657d2c9c3bb103f6077c7a394c661451d4a5bf1ece60834b5439ba2e4a3e6e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - refine --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: refine is a React-based framework for building internal tools, rapidly.
  homepage: https://refine.dev
  repository: https://github.com/refinedev/refine

extra:
  recipe-maintainers:
    - danielnachun
