context:
  version: "2.16.42"

package:
  name: refinedev-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@refinedev/cli/-/cli-${{ version }}.tgz
  sha256: 9d7efd90ba3b8964e9436af056a962b0744c2829ee43e2c0e13098a2429c6fb0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "refine 2>&1 | grep -q \"package.json not found\""

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: refine is a React-based framework for building internal tools, rapidly.
  homepage: https://refine.dev
  repository: https://github.com/refinedev/refine

extra:
  recipe-maintainers:
    - danielnachun
