context:
  version: "2.16.49"

package:
  name: refinedev-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@refinedev/cli/-/cli-${{ version }}.tgz
  sha256: 06e526d806b6bb145f33a5706e59ad3ca942ee5a58a065d75260182ad9fc930e

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - refine --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: refine is a React-based framework for building internal tools, rapidly.
  homepage: https://refine.dev
  repository: https://github.com/refinedev/refine

extra:
  recipe-maintainers:
    - danielnachun
