context:
  version: "2.16.51"

package:
  name: refinedev-cli
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@refinedev/cli/-/cli-${{ version }}.tgz
  sha256: 4c9ff8e17c2c7bfe48c94053f07162974f13e114b4b7a08a3098e3201238b53c

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - refine --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: refine is a React-based framework for building internal tools, rapidly.
  homepage: https://refine.dev
  repository: https://github.com/refinedev/refine

extra:
  recipe-maintainers:
    - danielnachun
